// Generated by DVPE - Untitled Patch
// 2025-12-14T21:41:24.085Z

#include "daisy_field.h"
#include "daisysp.h"

using namespace daisy;
using namespace daisysp;

// Hardware
DaisyField hw;

// DSP Modules
Oscillator oscillator_b72d6b32;
MoogLadder moog_ladder_52be1907;
AdEnv ad_env_69c74f9a;

// Signal Variables
float sig_oscillator_b72d6b32_out = 0.0f;
float sig_moog_ladder_52be1907_out = 0.0f;
float cv_ad_env_69c74f9a_out = 0.0f;
float cv_knob_875185cc_out = 0.0f;
float cv_knob_b1a981fa_out = 0.0f;
float cv_knob_109504d9_out = 0.0f;
float cv_knob_0511d40d_out = 0.0f;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {
    hw.ProcessAllControls();

    // Read hardware controls
    float knob_knob_875185cc = hw.knob[1].Value();
    float knob_knob_b1a981fa = hw.knob[2].Value();
    float knob_knob_109504d9 = hw.knob[0].Value();
    float knob_knob_0511d40d = hw.knob[3].Value();

    // Read keyboard

    for (size_t i = 0; i < size; i++) {

        // OSCILLATOR
        oscillator_b72d6b32.SetFreq(440f * (1.0f + cv_knob_109504d9_out));
        sig_oscillator_b72d6b32_out = oscillator_b72d6b32.Process();

        // AD ENVELOPE
        cv_ad_env_69c74f9a_out = ad_env_69c74f9a.Process(false);

        // KNOB
        cv_knob_875185cc_out = 0f + (hw.knob[1].Value() * 1f);

        // KNOB
        cv_knob_b1a981fa_out = 0f + (hw.knob[2].Value() * 1f);

        // KNOB
        cv_knob_109504d9_out = 0f + (hw.knob[0].Value() * 1f);

        // KNOB
        cv_knob_0511d40d_out = 0f + (hw.knob[3].Value() * 1f);

        // MOOG LADDER
        moog_ladder_52be1907.SetFreq(1000f + (cv_ad_env_69c74f9a_out * 10000.0f));
        sig_moog_ladder_52be1907_out = moog_ladder_52be1907.Process(sig_oscillator_b72d6b32_out);

        // Output
        out[0][i] = sig_moog_ladder_52be1907_out;
        out[1][i] = sig_moog_ladder_52be1907_out;
    }
}

int main(void) {
    hw.Init();
    hw.SetAudioBlockSize(48);
    float sr = hw.AudioSampleRate();

    // Initialize DSP modules
    oscillator_b72d6b32.Init(sr);
    oscillator_b72d6b32.SetFreq(440f);
    oscillator_b72d6b32.SetAmp(0.5f);
    oscillator_b72d6b32.SetWaveform(Oscillator::WAVE_POLYBLEP_SAW);
    oscillator_b72d6b32.SetPw(0.5f);
    ad_env_69c74f9a.Init(sr);
    ad_env_69c74f9a.SetTime(0.01f);
    ad_env_69c74f9a.SetTime(0.5f);
    ad_env_69c74f9a.SetCurve(0f);
    moog_ladder_52be1907.Init(sr);
    moog_ladder_52be1907.SetFreq(1000f);
    moog_ladder_52be1907.SetRes(0.4f);

    hw.StartAdc();
    hw.StartAudio(AudioCallback);

    while(1) {}
}