# Project Name
TARGET = untitled_patch

# Sources
CPP_SOURCES = main.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and target processor
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
OPT = -Os

# Includes
C_INCLUDES += -I$(DAISYSP_DIR)/Source

# Include Libraries
include $(SYSTEM_FILES_DIR)/Makefile
