# FM-Granular Synthesizer Makefile

# Project Name
TARGET = fm_granular

# Sources
CPP_SOURCES = fm_granular_main.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

