// Generated by DVPE - Untitled Patch
// 2025-12-14T20:21:34.486Z

#include "daisy_field.h"
#include "daisysp.h"

using namespace daisy;
using namespace daisysp;

// Hardware
DaisyField hw;

// DSP Modules
Particle particle_e1f4b724;
MoogLadder moog_ladder_952d9bc2;

// Signal Variables
float sig_particle_e1f4b724_out = 0.0f;
float sig_moog_ladder_952d9bc2_out = 0.0f;
float cv_knob_cfb0a2e6_out = 0.0f;
float cv_knob_966fb730_out = 0.0f;
float cv_knob_1e8f4a6d_out = 0.0f;
float cv_knob_44f78a29_out = 0.0f;
float cv_knob_aad53da2_out = 0.0f;
float cv_knob_b9fb5d7d_out = 0.0f;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {
    hw.ProcessAllControls();

    // Read hardware controls
    float knob_knob_cfb0a2e6 = hw.knob[0].Value();
    float knob_knob_966fb730 = hw.knob[1].Value();
    float knob_knob_1e8f4a6d = hw.knob[2].Value();
    float knob_knob_44f78a29 = hw.knob[3].Value();
    float knob_knob_aad53da2 = hw.knob[4].Value();
    float knob_knob_b9fb5d7d = hw.knob[5].Value();

    // Read keyboard

    for (size_t i = 0; i < size; i++) {

        // PARTICLE
        sig_particle_e1f4b724_out = particle_e1f4b724.Process(false);

        // KNOB
        cv_knob_cfb0a2e6_out = 0f + (hw.knob[0].Value() * 1f);

        // KNOB
        cv_knob_966fb730_out = 0f + (hw.knob[1].Value() * 1f);

        // KNOB
        cv_knob_1e8f4a6d_out = 0f + (hw.knob[2].Value() * 1f);

        // KNOB
        cv_knob_44f78a29_out = 0f + (hw.knob[3].Value() * 1f);

        // KNOB
        cv_knob_aad53da2_out = 0f + (hw.knob[4].Value() * 1f);

        // KNOB
        cv_knob_b9fb5d7d_out = 0f + (hw.knob[5].Value() * 1f);

        // MOOG LADDER
        moog_ladder_952d9bc2.SetFreq(1000f + (cv_knob_aad53da2_out * 10000.0f));
        sig_moog_ladder_952d9bc2_out = moog_ladder_952d9bc2.Process(sig_particle_e1f4b724_out);

        // Output
        out[0][i] = sig_moog_ladder_952d9bc2_out;
        out[1][i] = sig_moog_ladder_952d9bc2_out;
    }
}

int main(void) {
    hw.Init();
    hw.SetAudioBlockSize(48);
    float sr = hw.AudioSampleRate();

    // Initialize DSP modules
    particle_e1f4b724.Init(sr);
    particle_e1f4b724.SetDensity(0.5f);
    particle_e1f4b724.SetSpread(0.5f);
    particle_e1f4b724.SetFreq(440f);
    particle_e1f4b724.SetResonance(0.5f);
    moog_ladder_952d9bc2.Init(sr);
    moog_ladder_952d9bc2.SetFreq(1000f);
    moog_ladder_952d9bc2.SetRes(0.4f);

    hw.StartAdc();
    hw.StartAudio(AudioCallback);

    while(1) {}
}