/**
 * Code Generator
 * Generates C++ code for Daisy Field from DVPE patch graphs
 * Ported from dvpe with type adaptations for dvpe_CLD
 */

import {
    BlockInstance,
    Connection,
    BlockDefinition,
    SignalType,
    PortDirection,
} from '@/types';
import { BlockRegistry } from '@/core/blocks/BlockRegistry';
import { GraphAnalyzer, ProcessingOrder } from '@/core/graph/GraphAnalyzer';
import { HardwareMappingAnalyzer, HardwareMapping } from './analyzers/HardwareMappingAnalyzer';

// ============================================================================
// TYPES
// ============================================================================

export interface PatchMetadata {
    name: string;
    blockSize: number;
    sampleRate?: number;
}

export interface PatchGraph {
    blocks: BlockInstance[];
    connections: Connection[];
    metadata: PatchMetadata;
}

export interface GeneratedCode {
    mainCpp: string;
    makefile: string;
    errors: string[];
    warnings: string[];
}

// ============================================================================
// CODE GENERATOR
// ============================================================================

export class CodeGenerator {
    private patch: PatchGraph;
    private blockDefs: Map<string, BlockDefinition>;
    private processingOrder: ProcessingOrder;
    private hardwareMapping: HardwareMapping;

    constructor(patch: PatchGraph) {
        this.patch = patch;
        this.blockDefs = new Map();

        // Load block definitions
        patch.blocks.forEach(block => {
            const def = BlockRegistry.get(block.definitionId);
            if (def) {
                this.blockDefs.set(block.definitionId, def);
            }
        });

        // Analyze graph
        this.processingOrder = GraphAnalyzer.getProcessingOrder(
            patch.blocks,
            patch.connections,
            this.blockDefs
        );

        // Analyze hardware mapping
        this.hardwareMapping = HardwareMappingAnalyzer.analyze(patch.blocks, this.blockDefs);
    }

    generate(): GeneratedCode {
        const errors: string[] = [];
        const warnings: string[] = [];

        if (!this.processingOrder.valid) {
            return {
                mainCpp: '',
                makefile: '',
                errors: [this.processingOrder.error || 'Invalid graph'],
                warnings: [],
            };
        }

        const includes = this.generateIncludes();
        const declarations = this.generateDeclarations();
        const audioCallback = this.generateAudioCallback();
        const mainFunction = this.generateMain();

        const mainCpp = `${includes}

${declarations}

${audioCallback}

${mainFunction}`;

        const makefile = this.generateMakefile();

        return { mainCpp, makefile, errors, warnings };
    }

    // ===========================================================================
    // INCLUDES SECTION
    // ===========================================================================

    private generateIncludes(): string {
        return `// Generated by DVPE - ${this.patch.metadata.name}
// ${new Date().toISOString()}

#include "daisy_field.h"
#include "daisysp.h"

using namespace daisy;
using namespace daisysp;`;
    }

    // ===========================================================================
    // DECLARATIONS SECTION
    // ===========================================================================

    private generateDeclarations(): string {
        const lines: string[] = [];

        lines.push('// Hardware');
        lines.push('DaisyField hw;');
        lines.push('');
        lines.push('// DSP Modules');

        this.patch.blocks.forEach(block => {
            const def = this.blockDefs.get(block.definitionId);
            if (!def) return;

            // Skip I/O blocks without DSP class and inline math blocks
            const skipBlocks = [
                'audio_output', 'audio_input', 'knob', 'key', 'encoder', 'gate_trigger_in',
                // Inline math/utility blocks (no DaisySP class)
                'vca', 'mixer', 'add', 'multiply', 'subtract', 'divide',
                'gain', 'bypass', 'sample_delay', 'cv_to_freq', 'mux', 'demux', 'linear_vca',
                'dust', // Inline random impulse generator
                // Phase 4 inline blocks
                'pan', 'balance', 'softclip', 'hardclip', 'rectifier', 'slew', 'smooth', 'gate',
                'bitcrush', 'distortion', 'stereo_mixer', 'pitch_shifter',
                // Phase 5: Hardware I/O
                'midi_note', 'midi_cc', 'cv_input', 'cv_output', 'gate_output', 'led_output'
            ];
            if (skipBlocks.includes(def.id)) {
                return;
            }

            const instanceName = this.getInstanceName(block);
            const className = def.className.replace('daisysp::', '');

            lines.push(`${className} ${instanceName};`);
        });

        // Signal routing variables
        lines.push('');
        lines.push('// Signal Variables');

        this.patch.blocks.forEach(block => {
            const def = this.blockDefs.get(block.definitionId);
            if (!def) return;

            const instanceName = this.getInstanceName(block);

            // Audio outputs
            def.ports
                .filter(p => p.signalType === SignalType.AUDIO && p.direction === PortDirection.OUTPUT)
                .forEach(port => {
                    lines.push(`float sig_${instanceName}_${port.id} = 0.0f;`);
                });

            // CV outputs
            def.ports
                .filter(p => p.signalType === SignalType.CV && p.direction === PortDirection.OUTPUT)
                .forEach(port => {
                    lines.push(`float cv_${instanceName}_${port.id} = 0.0f;`);
                });

            // Gate/Trigger outputs
            def.ports
                .filter(p => p.signalType === SignalType.TRIGGER && p.direction === PortDirection.OUTPUT)
                .forEach(port => {
                    lines.push(`bool gate_${instanceName}_${port.id} = false;`);
                });
        });

        return lines.join('\n');
    }

    // ===========================================================================
    // AUDIO CALLBACK
    // ===========================================================================

    private generateAudioCallback(): string {
        const lines: string[] = [];

        lines.push('void AudioCallback(AudioHandle::InputBuffer in,');
        lines.push('                   AudioHandle::OutputBuffer out,');
        lines.push('                   size_t size) {');
        lines.push('    hw.ProcessAllControls();');
        lines.push('');

        // Read knobs
        lines.push('    // Read hardware controls');
        this.hardwareMapping.knobs.forEach((blockId, index) => {
            const block = this.patch.blocks.find(b => b.id === blockId);
            if (block) {
                const instanceName = this.getInstanceName(block);
                lines.push(`    float knob_${instanceName} = hw.knob[${index}].Value();`);
            }
        });

        // Read keys
        lines.push('');
        lines.push('    // Read keyboard');
        this.hardwareMapping.keys.forEach((blockId, index) => {
            const block = this.patch.blocks.find(b => b.id === blockId);
            if (block) {
                const instanceName = this.getInstanceName(block);
                lines.push(`    bool key_${instanceName} = hw.KeyboardState(${index});`);
            }
        });

        lines.push('');
        lines.push('    for (size_t i = 0; i < size; i++) {');

        // Generate processing code for each block in order
        this.processingOrder.blocks.forEach(blockId => {
            const block = this.patch.blocks.find(b => b.id === blockId);
            if (!block) return;

            const def = this.blockDefs.get(block.definitionId);
            if (!def) return;

            const code = this.generateBlockProcessing(block, def);
            if (code.length > 0) {
                lines.push('');
                lines.push(`        // ${def.displayName}`);
                code.forEach(line => lines.push('        ' + line));
            }
        });

        // Output assignment
        lines.push('');
        lines.push('        // Output');
        const outputCode = this.generateOutputAssignment();
        outputCode.forEach(line => lines.push('        ' + line));

        lines.push('    }');
        lines.push('}');

        return lines.join('\n');
    }

    // ===========================================================================
    // BLOCK-SPECIFIC CODE GENERATORS
    // ===========================================================================

    private generateBlockProcessing(block: BlockInstance, def: BlockDefinition): string[] {
        const lines: string[] = [];
        const instanceName = this.getInstanceName(block);

        switch (def.id) {
            case 'oscillator':
                lines.push(...this.generateOscillatorCode(block, instanceName));
                break;
            case 'fm2':
                lines.push(...this.generateFm2Code(block, instanceName));
                break;
            case 'particle':
                lines.push(...this.generateParticleCode(block, instanceName));
                break;
            case 'grainlet_oscillator':
                lines.push(...this.generateGrainletCode(block, instanceName));
                break;
            case 'moog_ladder':
                lines.push(...this.generateMoogLadderCode(block, instanceName));
                break;
            case 'svf':
                lines.push(...this.generateSvfCode(block, instanceName));
                break;
            case 'adsr':
                lines.push(...this.generateAdsrCode(block, instanceName));
                break;
            case 'ad_env':
                lines.push(...this.generateAdEnvCode(block, instanceName));
                break;
            case 'vca':
                lines.push(...this.generateVcaCode(block, instanceName));
                break;
            case 'mixer':
                lines.push(...this.generateMixerCode(block, instanceName));
                break;
            case 'delay':
                lines.push(...this.generateDelayCode(block, instanceName));
                break;
            case 'reverb':
                lines.push(...this.generateReverbCode(block, instanceName));
                break;
            case 'compressor':
                lines.push(...this.generateCompressorCode(block, instanceName));
                break;
            case 'overdrive':
                lines.push(...this.generateOverdriveCode(block, instanceName));
                break;
            case 'knob':
                lines.push(...this.generateKnobCode(block, instanceName));
                break;
            case 'key':
                lines.push(...this.generateKeyCode(block, instanceName));
                break;
            case 'gate_trigger_in':
                lines.push(...this.generateGateTriggerInCode(block, instanceName));
                break;
            case 'encoder':
                lines.push(...this.generateEncoderCode(block, instanceName));
                break;
            // ===== PHASE 1: Core DSP Blocks =====
            case 'lfo':
                lines.push(...this.generateLfoCode(block, instanceName));
                break;
            case 'whitenoise':
                lines.push(...this.generateWhiteNoiseCode(block, instanceName));
                break;
            case 'chorus':
                lines.push(...this.generateChorusCode(block, instanceName));
                break;
            case 'flanger':
                lines.push(...this.generateFlangerCode(block, instanceName));
                break;
            case 'onepole':
                lines.push(...this.generateOnePoleCode(block, instanceName));
                break;
            case 'atone':
                lines.push(...this.generateAToneCode(block, instanceName));
                break;
            case 'dcblock':
                lines.push(...this.generateDCBlockCode(block, instanceName));
                break;
            case 'limiter':
                lines.push(...this.generateLimiterCode(block, instanceName));
                break;
            case 'fold':
                lines.push(...this.generateFoldCode(block, instanceName));
                break;
            // ===== PHASE 2: Math & Utility Blocks =====
            case 'add':
                lines.push(...this.generateAddCode(block, instanceName));
                break;
            case 'multiply':
                lines.push(...this.generateMultiplyCode(block, instanceName));
                break;
            case 'subtract':
                lines.push(...this.generateSubtractCode(block, instanceName));
                break;
            case 'divide':
                lines.push(...this.generateDivideCode(block, instanceName));
                break;
            case 'gain':
                lines.push(...this.generateGainCode(block, instanceName));
                break;
            case 'bypass':
                lines.push(...this.generateBypassCode(block, instanceName));
                break;
            case 'sample_delay':
                lines.push(...this.generateSampleDelayCode(block, instanceName));
                break;
            case 'cv_to_freq':
                lines.push(...this.generateCvToFreqCode(block, instanceName));
                break;
            case 'mux':
                lines.push(...this.generateMuxCode(block, instanceName));
                break;
            case 'demux':
                lines.push(...this.generateDemuxCode(block, instanceName));
                break;
            case 'linear_vca':
                lines.push(...this.generateLinearVcaCode(block, instanceName));
                break;
            // ===== PHASE 3: Drums =====
            case 'hihat':
                lines.push(...this.generateHiHatCode(block, instanceName));
                break;
            case 'analog_bass_drum':
                lines.push(...this.generateAnalogBassDrumCode(block, instanceName));
                break;
            case 'analog_snare_drum':
                lines.push(...this.generateAnalogSnareDrumCode(block, instanceName));
                break;
            case 'synth_bass_drum':
                lines.push(...this.generateSynthBassDrumCode(block, instanceName));
                break;
            case 'synth_snare_drum':
                lines.push(...this.generateSynthSnareDrumCode(block, instanceName));
                break;
            // ===== PHASE 3: Physical Modeling & Effects =====
            case 'drip':
                lines.push(...this.generateDripCode(block, instanceName));
                break;
            case 'modal_voice':
                lines.push(...this.generateModalVoiceCode(block, instanceName));
                break;
            case 'string_voice':
                lines.push(...this.generateStringVoiceCode(block, instanceName));
                break;
            case 'wavefolder':
                lines.push(...this.generateWavefolderCode(block, instanceName));
                break;
            case 'dust':
                lines.push(...this.generateDustCode(block, instanceName));
                break;
            // ===== PHASE 4A: Advanced Effects =====
            case 'decimator':
                lines.push(...this.generateDecimatorCode(block, instanceName));
                break;
            case 'phaser':
                lines.push(...this.generatePhaserCode(block, instanceName));
                break;
            case 'tremolo':
                lines.push(...this.generateTremoloCode(block, instanceName));
                break;
            case 'autowah':
                lines.push(...this.generateAutowahCode(block, instanceName));
                break;
            case 'resonator':
                lines.push(...this.generateResonatorCode(block, instanceName));
                break;
            case 'pluck':
                lines.push(...this.generatePluckCode(block, instanceName));
                break;
            case 'crossfade':
                lines.push(...this.generateCrossFadeCode(block, instanceName));
                break;
            case 'sample_rate_reducer':
                lines.push(...this.generateSampleRateReducerCode(block, instanceName));
                break;
            // ===== PHASE 4B: Inline Utilities =====
            case 'pan':
                lines.push(...this.generatePanCode(block, instanceName));
                break;
            case 'balance':
                lines.push(...this.generateBalanceCode(block, instanceName));
                break;
            case 'softclip':
                lines.push(...this.generateSoftClipCode(block, instanceName));
                break;
            case 'hardclip':
                lines.push(...this.generateHardClipCode(block, instanceName));
                break;
            case 'rectifier':
                lines.push(...this.generateRectifierCode(block, instanceName));
                break;
            case 'slew':
                lines.push(...this.generateSlewCode(block, instanceName));
                break;
            case 'smooth':
                lines.push(...this.generateSmoothCode(block, instanceName));
                break;
            case 'gate':
                lines.push(...this.generateGateCode(block, instanceName));
                break;
            // ===== PHASE 4C: Complex Blocks =====
            case 'bitcrush':
                lines.push(...this.generateBitcrushCode(block, instanceName));
                break;
            case 'distortion':
                lines.push(...this.generateDistortionCode(block, instanceName));
                break;
            case 'stereo_mixer':
                lines.push(...this.generateStereoMixerCode(block, instanceName));
                break;
            case 'pitch_shifter':
                lines.push(...this.generatePitchShifterCode(block, instanceName));
                break;
            // ===== PHASE 5: Hardware I/O =====
            case 'midi_note':
                lines.push(...this.generateMidiNoteCode(block, instanceName));
                break;
            case 'midi_cc':
                lines.push(...this.generateMidiCCCode(block, instanceName));
                break;
            case 'cv_input':
                lines.push(...this.generateCVInputCode(block, instanceName));
                break;
            case 'cv_output':
                lines.push(...this.generateCVOutputCode(block, instanceName));
                break;
            case 'gate_output':
                lines.push(...this.generateGateOutputCode(block, instanceName));
                break;
            case 'led_output':
                lines.push(...this.generateLEDOutputCode(block, instanceName));
                break;
        }

        return lines;
    }

    private generateOscillatorCode(block: BlockInstance, name: string): string[] {
        const freqCV = this.getInputConnection(block.id, 'freq_cv');
        if (freqCV) {
            const sourceVar = this.getSourceVariable(freqCV);
            const baseFreq = block.parameterValues['frequency'] ?? 440;
            return [
                `${name}.SetFreq(${this.formatFloat(baseFreq)} * (1.0f + ${sourceVar}));`,
                `sig_${name}_out = ${name}.Process();`,
            ];
        }
        return [`sig_${name}_out = ${name}.Process();`];
    }

    private generateFm2Code(block: BlockInstance, name: string): string[] {
        const freqCV = this.getInputConnection(block.id, 'freq_cv');
        const lines: string[] = [];

        if (freqCV) {
            const sourceVar = this.getSourceVariable(freqCV);
            const baseFreq = block.parameterValues['frequency'] ?? 440;
            lines.push(`${name}.SetFrequency(${this.formatFloat(baseFreq)} * (1.0f + ${sourceVar}));`);
        }

        lines.push(`sig_${name}_out = ${name}.Process();`);
        return lines;
    }

    private generateParticleCode(block: BlockInstance, name: string): string[] {
        const syncIn = this.getInputConnection(block.id, 'sync');
        const syncVar = syncIn ? this.getSourceVariable(syncIn) : 'false';
        return [`sig_${name}_out = ${name}.Process(${syncVar});`];
    }

    private generateGrainletCode(_block: BlockInstance, name: string): string[] {
        return [`sig_${name}_out = ${name}.Process();`];
    }

    private generateMoogLadderCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';

        const freqCV = this.getInputConnection(block.id, 'freq_cv');
        const lines: string[] = [];

        if (freqCV) {
            const sourceVar = this.getSourceVariable(freqCV);
            const baseCutoff = block.parameterValues['cutoff'] ?? 1000;
            lines.push(`${name}.SetFreq(${this.formatFloat(baseCutoff)} + (${sourceVar} * 10000.0f));`);
        }

        lines.push(`sig_${name}_out = ${name}.Process(${inputVar});`);
        return lines;
    }

    private generateSvfCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';

        return [
            `${name}.Process(${inputVar});`,
            `sig_${name}_low = ${name}.Low();`,
            `sig_${name}_high = ${name}.High();`,
            `sig_${name}_band = ${name}.Band();`,
            `sig_${name}_notch = ${name}.Notch();`,
        ];
    }

    private generateAdsrCode(block: BlockInstance, name: string): string[] {
        const gateIn = this.getInputConnection(block.id, 'gate');
        const gateVar = gateIn ? this.getSourceVariable(gateIn) : 'false';
        return [`cv_${name}_out = ${name}.Process(${gateVar});`];
    }

    private generateAdEnvCode(block: BlockInstance, name: string): string[] {
        const trigIn = this.getInputConnection(block.id, 'trigger');
        const trigVar = trigIn ? this.getSourceVariable(trigIn) : 'false';
        return [`cv_${name}_out = ${name}.Process(${trigVar});`];
    }

    private generateVcaCode(block: BlockInstance, name: string): string[] {
        // VCA is not a DaisySP class - implemented as inline multiplication
        const audioIn = this.getInputConnection(block.id, 'in');
        const cvIn = this.getInputConnection(block.id, 'cv');

        const audioVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        const cvVar = cvIn ? this.getSourceVariable(cvIn) : '1.0f';
        const gain = block.parameterValues['gain'] ?? 1.0;

        return [`sig_${name}_out = ${audioVar} * ${cvVar} * ${this.formatFloat(gain)};`];
    }

    private generateMixerCode(block: BlockInstance, name: string): string[] {
        // Mixer is not a DaisySP class - implemented as inline addition
        const channels = ['ch1', 'ch2', 'ch3', 'ch4'];
        const mixTerms: string[] = [];

        channels.forEach(ch => {
            const conn = this.getInputConnection(block.id, ch);
            if (conn) {
                const sourceVar = this.getSourceVariable(conn);
                const level = block.parameterValues[`${ch}_level`] ?? 0.8;
                mixTerms.push(`(${sourceVar} * ${this.formatFloat(level)})`);
            }
        });

        if (mixTerms.length > 0) {
            return [`sig_${name}_out = ${mixTerms.join(' + ')};`];
        }
        return [`sig_${name}_out = 0.0f;`];
    }

    private generateDelayCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        const feedback = block.parameterValues['feedback'] ?? 0.5;

        return [
            `float delayed = ${name}.Read();`,
            `${name}.Write(${inputVar} + delayed * ${this.formatFloat(feedback)});`,
            `sig_${name}_out = delayed;`,
        ];
    }

    private generateReverbCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';

        return [
            `float revL, revR;`,
            `${name}.Process(${inputVar}, ${inputVar}, &revL, &revR);`,
            `sig_${name}_left = revL;`,
            `sig_${name}_right = revR;`,
        ];
    }

    private generateCompressorCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generateOverdriveCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generateKnobCode(block: BlockInstance, name: string): string[] {
        const channel = parseInt(block.parameterValues['channel'] as string) || 0;
        const min = block.parameterValues['min'] ?? 0;
        const max = block.parameterValues['max'] ?? 1;
        const range = (max as number) - (min as number);

        return [`cv_${name}_out = ${this.formatFloat(min)} + (hw.knob[${channel}].Value() * ${this.formatFloat(range)});`];
    }

    private generateKeyCode(block: BlockInstance, name: string): string[] {
        const note = block.parameterValues['note'] ?? 60;
        const freq = 440.0 * Math.pow(2, ((note as number) - 69) / 12);

        // Find key index
        let keyIndex = 0;
        this.hardwareMapping.keys.forEach((blockId, idx) => {
            if (blockId === block.id) keyIndex = idx;
        });

        return [
            `cv_${name}_cv = ${freq.toFixed(2)}f;`,
            `gate_${name}_gate = hw.KeyboardState(${keyIndex});`,
        ];
    }

    private generateGateTriggerInCode(block: BlockInstance, name: string): string[] {
        const channel = parseInt(block.parameterValues['channel'] as string) || 0;

        // Daisy Field has 2 gate inputs, mapped to index 0 and 1
        return [
            `gate_${name}_gate = hw.GateInput[${channel}].State();`,
            `gate_${name}_trig = hw.GateInput[${channel}].Trig();`,
        ];
    }

    private generateEncoderCode(_block: BlockInstance, name: string): string[] {
        return [
            `// [WARNING] Encoder block is not supported on Daisy Field hardware`,
            `cv_${name}_value = 0.0f;`,
            `cv_${name}_increment = 0.0f;`,
            `gate_${name}_press = false;`,
        ];
    }

    // ===========================================================================
    // PHASE 1: CORE DSP BLOCK GENERATORS
    // ===========================================================================

    private generateLfoCode(block: BlockInstance, name: string): string[] {
        const rateCV = this.getInputConnection(block.id, 'rate_cv');
        const lines: string[] = [];

        if (rateCV) {
            const sourceVar = this.getSourceVariable(rateCV);
            const baseRate = block.parameterValues['freq'] ?? 1;
            lines.push(`${name}.SetFreq(${this.formatFloat(baseRate)} * (1.0f + ${sourceVar}));`);
        }

        lines.push(`cv_${name}_out = ${name}.Process();`);
        return lines;
    }

    private generateWhiteNoiseCode(_block: BlockInstance, name: string): string[] {
        // WhiteNoise.Process() returns audio sample
        return [`sig_${name}_out = ${name}.Process();`];
    }

    private generateChorusCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generateFlangerCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generateOnePoleCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generateAToneCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generateDCBlockCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generateLimiterCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generateFoldCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    // ===========================================================================
    // PHASE 2: MATH & UTILITY BLOCK GENERATORS (Inline implementations)
    // ===========================================================================

    private generateAddCode(block: BlockInstance, name: string): string[] {
        // Add is inline - sum multiple inputs
        const inputs = ['in1', 'in2', 'in3', 'in4'];
        const terms: string[] = [];

        inputs.forEach(inputId => {
            const conn = this.getInputConnection(block.id, inputId);
            if (conn) {
                terms.push(this.getSourceVariable(conn));
            }
        });

        if (terms.length > 0) {
            return [`sig_${name}_out = ${terms.join(' + ')};`];
        }
        return [`sig_${name}_out = 0.0f;`];
    }

    private generateMultiplyCode(block: BlockInstance, name: string): string[] {
        // Multiply is inline
        const in1 = this.getInputConnection(block.id, 'in1');
        const in2 = this.getInputConnection(block.id, 'in2');

        const var1 = in1 ? this.getSourceVariable(in1) : '1.0f';
        const var2 = in2 ? this.getSourceVariable(in2) : '1.0f';

        return [`sig_${name}_out = ${var1} * ${var2};`];
    }

    private generateSubtractCode(block: BlockInstance, name: string): string[] {
        // Subtract is inline
        const in1 = this.getInputConnection(block.id, 'in1');
        const in2 = this.getInputConnection(block.id, 'in2');

        const var1 = in1 ? this.getSourceVariable(in1) : '0.0f';
        const var2 = in2 ? this.getSourceVariable(in2) : '0.0f';

        return [`sig_${name}_out = ${var1} - ${var2};`];
    }

    private generateDivideCode(block: BlockInstance, name: string): string[] {
        // Divide is inline with protection against division by zero
        const in1 = this.getInputConnection(block.id, 'in1');
        const in2 = this.getInputConnection(block.id, 'in2');

        const var1 = in1 ? this.getSourceVariable(in1) : '0.0f';
        const var2 = in2 ? this.getSourceVariable(in2) : '1.0f';

        return [`sig_${name}_out = ${var1} / fmaxf(fabsf(${var2}), 0.0001f);`];
    }

    private generateGainCode(block: BlockInstance, name: string): string[] {
        // Gain is inline multiplication
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        const gain = block.parameterValues['gain'] ?? 1.0;

        return [`sig_${name}_out = ${inputVar} * ${this.formatFloat(gain)};`];
    }

    private generateBypassCode(block: BlockInstance, name: string): string[] {
        // Bypass is just a passthrough
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';

        return [`sig_${name}_out = ${inputVar};`];
    }

    private generateSampleDelayCode(block: BlockInstance, name: string): string[] {
        // Sample delay (z^-1) using static variable
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';

        return [
            `sig_${name}_out = ${name}_prev;`,
            `${name}_prev = ${inputVar};`,
        ];
    }

    private generateCvToFreqCode(block: BlockInstance, name: string): string[] {
        // CV to Frequency: 1V/Oct standard conversion
        // CV of 0 = 440Hz (A4), each volt is an octave
        const cvIn = this.getInputConnection(block.id, 'cv_in');
        const cvVar = cvIn ? this.getSourceVariable(cvIn) : '0.0f';

        return [`cv_${name}_freq = 440.0f * powf(2.0f, ${cvVar});`];
    }

    private generateMuxCode(block: BlockInstance, name: string): string[] {
        // Mux: select one of multiple inputs based on selector CV
        const selector = this.getInputConnection(block.id, 'selector');
        const in1 = this.getInputConnection(block.id, 'in1');
        const in2 = this.getInputConnection(block.id, 'in2');

        const selectorVar = selector ? this.getSourceVariable(selector) : '0.0f';
        const var1 = in1 ? this.getSourceVariable(in1) : '0.0f';
        const var2 = in2 ? this.getSourceVariable(in2) : '0.0f';

        return [`sig_${name}_out = (${selectorVar} < 0.5f) ? ${var1} : ${var2};`];
    }

    private generateDemuxCode(block: BlockInstance, name: string): string[] {
        // Demux: route input to one of multiple outputs based on selector
        const selector = this.getInputConnection(block.id, 'selector');
        const audioIn = this.getInputConnection(block.id, 'in');

        const selectorVar = selector ? this.getSourceVariable(selector) : '0.0f';
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';

        return [
            `sig_${name}_out1 = (${selectorVar} < 0.5f) ? ${inputVar} : 0.0f;`,
            `sig_${name}_out2 = (${selectorVar} >= 0.5f) ? ${inputVar} : 0.0f;`,
        ];
    }

    private generateLinearVcaCode(block: BlockInstance, name: string): string[] {
        // LinearVCA is inline multiplication (no DaisySP class)
        const audioIn = this.getInputConnection(block.id, 'in');
        const cvIn = this.getInputConnection(block.id, 'cv');

        const audioVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        const cvVar = cvIn ? this.getSourceVariable(cvIn) : '1.0f';

        return [`sig_${name}_out = ${audioVar} * ${cvVar};`];
    }

    // ===========================================================================
    // PHASE 3: DRUMS BLOCK GENERATORS
    // ===========================================================================

    private generateHiHatCode(block: BlockInstance, name: string): string[] {
        const trigIn = this.getInputConnection(block.id, 'trig');
        const trigVar = trigIn ? this.getSourceVariable(trigIn) : 'false';
        return [`sig_${name}_out = ${name}.Process(${trigVar});`];
    }

    private generateAnalogBassDrumCode(block: BlockInstance, name: string): string[] {
        const trigIn = this.getInputConnection(block.id, 'trig');
        const trigVar = trigIn ? this.getSourceVariable(trigIn) : 'false';
        return [`sig_${name}_out = ${name}.Process(${trigVar});`];
    }

    private generateAnalogSnareDrumCode(block: BlockInstance, name: string): string[] {
        const trigIn = this.getInputConnection(block.id, 'trig');
        const trigVar = trigIn ? this.getSourceVariable(trigIn) : 'false';
        return [`sig_${name}_out = ${name}.Process(${trigVar});`];
    }

    private generateSynthBassDrumCode(block: BlockInstance, name: string): string[] {
        const trigIn = this.getInputConnection(block.id, 'trig');
        const trigVar = trigIn ? this.getSourceVariable(trigIn) : 'false';
        return [`sig_${name}_out = ${name}.Process(${trigVar});`];
    }

    private generateSynthSnareDrumCode(block: BlockInstance, name: string): string[] {
        const trigIn = this.getInputConnection(block.id, 'trig');
        const trigVar = trigIn ? this.getSourceVariable(trigIn) : 'false';
        return [`sig_${name}_out = ${name}.Process(${trigVar});`];
    }

    // ===========================================================================
    // PHASE 3: PHYSICAL MODELING BLOCK GENERATORS
    // ===========================================================================

    private generateDripCode(block: BlockInstance, name: string): string[] {
        const trigIn = this.getInputConnection(block.id, 'trig');
        const trigVar = trigIn ? this.getSourceVariable(trigIn) : 'false';
        return [`sig_${name}_out = ${name}.Process(${trigVar});`];
    }

    private generateModalVoiceCode(block: BlockInstance, name: string): string[] {
        const trigIn = this.getInputConnection(block.id, 'trig');
        const freqCV = this.getInputConnection(block.id, 'freq_cv');
        const lines: string[] = [];

        if (freqCV) {
            const freqVar = this.getSourceVariable(freqCV);
            const baseFreq = block.parameterValues['freq'] ?? 220;
            lines.push(`${name}.SetFreq(${this.formatFloat(baseFreq)} * (1.0f + ${freqVar}));`);
        }

        const trigVar = trigIn ? this.getSourceVariable(trigIn) : 'false';
        lines.push(`sig_${name}_out = ${name}.Process(${trigVar});`);
        return lines;
    }

    private generateStringVoiceCode(block: BlockInstance, name: string): string[] {
        const trigIn = this.getInputConnection(block.id, 'trig');
        const freqCV = this.getInputConnection(block.id, 'freq_cv');
        const lines: string[] = [];

        if (freqCV) {
            const freqVar = this.getSourceVariable(freqCV);
            const baseFreq = block.parameterValues['freq'] ?? 220;
            lines.push(`${name}.SetFreq(${this.formatFloat(baseFreq)} * (1.0f + ${freqVar}));`);
        }

        const trigVar = trigIn ? this.getSourceVariable(trigIn) : 'false';
        lines.push(`sig_${name}_out = ${name}.Process(${trigVar});`);
        return lines;
    }

    private generateWavefolderCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const gainCV = this.getInputConnection(block.id, 'gain_cv');
        const lines: string[] = [];

        if (gainCV) {
            const gainVar = this.getSourceVariable(gainCV);
            const baseGain = block.parameterValues['gain'] ?? 1.0;
            lines.push(`${name}.SetGain(${this.formatFloat(baseGain)} * (1.0f + ${gainVar}));`);
        }

        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        lines.push(`sig_${name}_out = ${name}.Process(${inputVar});`);
        return lines;
    }

    private generateDustCode(block: BlockInstance, name: string): string[] {
        // Dust is inline random impulse generator
        const densityCV = this.getInputConnection(block.id, 'density_cv');
        const density = block.parameterValues['density'] ?? 10.0;
        const amp = block.parameterValues['amp'] ?? 0.5;

        const lines: string[] = [];
        let densityVal = this.formatFloat(density);
        if (densityCV) {
            const cvVar = this.getSourceVariable(densityCV);
            densityVal = `${this.formatFloat(density)} * (1.0f + ${cvVar})`;
        }

        // Inline dust implementation: random impulse based on density
        lines.push(`float ${name}_rand = (float)rand() / (float)RAND_MAX;`);
        lines.push(`float ${name}_thresh = ${densityVal} / sr;`);
        lines.push(`sig_${name}_out = (${name}_rand < ${name}_thresh) ? ${this.formatFloat(amp)} : 0.0f;`);
        lines.push(`gate_${name}_trig_out = (${name}_rand < ${name}_thresh);`);
        return lines;
    }

    // ===========================================================================
    // PHASE 4A: ADVANCED EFFECTS BLOCK GENERATORS
    // ===========================================================================

    private generateDecimatorCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generatePhaserCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generateTremoloCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generateAutowahCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generateResonatorCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    private generatePluckCode(block: BlockInstance, name: string): string[] {
        const trigIn = this.getInputConnection(block.id, 'trig');
        const trigVar = trigIn ? this.getSourceVariable(trigIn) : 'false';
        return [`sig_${name}_out = ${name}.Process(${trigVar});`];
    }

    private generateCrossFadeCode(block: BlockInstance, name: string): string[] {
        const in1 = this.getInputConnection(block.id, 'in1');
        const in2 = this.getInputConnection(block.id, 'in2');
        const var1 = in1 ? this.getSourceVariable(in1) : '0.0f';
        const var2 = in2 ? this.getSourceVariable(in2) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${var1}, ${var2});`];
    }

    private generateSampleRateReducerCode(block: BlockInstance, name: string): string[] {
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        return [`sig_${name}_out = ${name}.Process(${inputVar});`];
    }

    // ===========================================================================
    // PHASE 4B: INLINE UTILITY BLOCK GENERATORS
    // ===========================================================================

    private generatePanCode(block: BlockInstance, name: string): string[] {
        // Pan is inline - mono to stereo panning
        const audioIn = this.getInputConnection(block.id, 'in');
        const panCV = this.getInputConnection(block.id, 'pan_cv');

        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        let panVal = this.formatFloat(block.parameterValues['pan'] ?? 0.5);
        if (panCV) {
            const cvVar = this.getSourceVariable(panCV);
            panVal = `fminf(1.0f, fmaxf(0.0f, ${panVal} + ${cvVar}))`;
        }

        return [
            `sig_${name}_left = ${inputVar} * sqrtf(1.0f - ${panVal});`,
            `sig_${name}_right = ${inputVar} * sqrtf(${panVal});`,
        ];
    }

    private generateBalanceCode(block: BlockInstance, name: string): string[] {
        // Balance is inline - stereo balance control
        const leftIn = this.getInputConnection(block.id, 'left_in');
        const rightIn = this.getInputConnection(block.id, 'right_in');
        const balCV = this.getInputConnection(block.id, 'balance_cv');

        const leftVar = leftIn ? this.getSourceVariable(leftIn) : '0.0f';
        const rightVar = rightIn ? this.getSourceVariable(rightIn) : '0.0f';
        let balVal = this.formatFloat(block.parameterValues['balance'] ?? 0.5);
        if (balCV) {
            const cvVar = this.getSourceVariable(balCV);
            balVal = `fminf(1.0f, fmaxf(0.0f, ${balVal} + ${cvVar}))`;
        }

        return [
            `sig_${name}_left_out = ${leftVar} * (1.0f - ${balVal});`,
            `sig_${name}_right_out = ${rightVar} * ${balVal};`,
        ];
    }

    private generateSoftClipCode(block: BlockInstance, name: string): string[] {
        // SoftClip is inline tanh saturation
        const audioIn = this.getInputConnection(block.id, 'in');
        const driveCV = this.getInputConnection(block.id, 'drive_cv');

        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        let driveVal = this.formatFloat(block.parameterValues['drive'] ?? 1.0);
        if (driveCV) {
            const cvVar = this.getSourceVariable(driveCV);
            driveVal = `fmaxf(0.1f, ${driveVal} * (1.0f + ${cvVar}))`;
        }

        return [`sig_${name}_out = tanhf(${inputVar} * ${driveVal}) / tanhf(${driveVal});`];
    }

    private generateHardClipCode(block: BlockInstance, name: string): string[] {
        // HardClip is inline clipping
        const audioIn = this.getInputConnection(block.id, 'in');
        const threshCV = this.getInputConnection(block.id, 'threshold_cv');

        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        let threshVal = this.formatFloat(block.parameterValues['threshold'] ?? 0.8);
        if (threshCV) {
            const cvVar = this.getSourceVariable(threshCV);
            threshVal = `fmaxf(0.01f, ${threshVal} * (1.0f + ${cvVar}))`;
        }

        return [`sig_${name}_out = fminf(fmaxf(${inputVar}, -${threshVal}), ${threshVal});`];
    }

    private generateRectifierCode(block: BlockInstance, name: string): string[] {
        // Rectifier is inline abs/max
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        const mode = block.parameterValues['mode'] ?? 0;

        if (mode === 1) {
            // Half-wave
            return [`sig_${name}_out = fmaxf(${inputVar}, 0.0f);`];
        }
        // Full-wave (default)
        return [`sig_${name}_out = fabsf(${inputVar});`];
    }

    private generateSlewCode(block: BlockInstance, name: string): string[] {
        // Slew limiter - inline one-pole with separate rise/fall
        const cvIn = this.getInputConnection(block.id, 'in');
        const inputVar = cvIn ? this.getSourceVariable(cvIn) : '0.0f';
        const rise = Number(block.parameterValues['rise'] ?? 0.01);
        const fall = Number(block.parameterValues['fall'] ?? 0.01);

        // Calculate coefficients from time constants
        return [
            `float ${name}_target = ${inputVar};`,
            `float ${name}_coef = (${name}_target > ${name}_prev) ? ${this.formatFloat(1.0 / (rise * 48000))} : ${this.formatFloat(1.0 / (fall * 48000))};`,
            `${name}_prev += (${name}_target - ${name}_prev) * fminf(${name}_coef, 1.0f);`,
            `cv_${name}_out = ${name}_prev;`,
        ];
    }

    private generateSmoothCode(block: BlockInstance, name: string): string[] {
        // Smooth is inline one-pole lowpass
        const cvIn = this.getInputConnection(block.id, 'in');
        const inputVar = cvIn ? this.getSourceVariable(cvIn) : '0.0f';
        const smooth = block.parameterValues['smooth'] ?? 0.99;

        return [
            `${name}_prev = ${name}_prev * ${this.formatFloat(smooth)} + ${inputVar} * ${this.formatFloat(1.0 - (smooth as number))};`,
            `cv_${name}_out = ${name}_prev;`,
        ];
    }

    private generateGateCode(block: BlockInstance, name: string): string[] {
        // Gate is inline threshold comparison
        const audioIn = this.getInputConnection(block.id, 'in');
        const threshCV = this.getInputConnection(block.id, 'threshold_cv');

        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        let threshVal = this.formatFloat(block.parameterValues['threshold'] ?? 0.01);
        if (threshCV) {
            const cvVar = this.getSourceVariable(threshCV);
            threshVal = `fmaxf(0.0f, ${threshVal} + ${cvVar} * 0.5f)`;
        }

        return [`sig_${name}_out = (fabsf(${inputVar}) > ${threshVal}) ? ${inputVar} : 0.0f;`];
    }

    // ===========================================================================
    // PHASE 4C: COMPLEX BLOCK GENERATORS
    // ===========================================================================

    private generateBitcrushCode(block: BlockInstance, name: string): string[] {
        // Bitcrush is inline quantization
        const audioIn = this.getInputConnection(block.id, 'in');
        const bitsCV = this.getInputConnection(block.id, 'bits_cv');

        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        let bitsVal = this.formatFloat(block.parameterValues['bits'] ?? 8);
        if (bitsCV) {
            const cvVar = this.getSourceVariable(bitsCV);
            bitsVal = `fmaxf(1.0f, fminf(16.0f, ${bitsVal} + ${cvVar} * 8.0f))`;
        }

        return [
            `float ${name}_levels = powf(2.0f, ${bitsVal});`,
            `sig_${name}_out = roundf(${inputVar} * ${name}_levels) / ${name}_levels;`,
        ];
    }

    private generateDistortionCode(block: BlockInstance, name: string): string[] {
        // Distortion is inline waveshaping
        const audioIn = this.getInputConnection(block.id, 'in');
        const driveCV = this.getInputConnection(block.id, 'drive_cv');

        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        let driveVal = this.formatFloat(block.parameterValues['drive'] ?? 0.5);
        if (driveCV) {
            const cvVar = this.getSourceVariable(driveCV);
            driveVal = `fminf(1.0f, fmaxf(0.0f, ${driveVal} + ${cvVar}))`;
        }
        const level = block.parameterValues['level'] ?? 0.5;

        return [
            `float ${name}_k = 2.0f * ${driveVal} / (1.0f - ${driveVal} + 0.01f);`,
            `sig_${name}_out = (1.0f + ${name}_k) * ${inputVar} / (1.0f + ${name}_k * fabsf(${inputVar})) * ${this.formatFloat(level)};`,
        ];
    }

    private generateStereoMixerCode(block: BlockInstance, name: string): string[] {
        // StereoMixer is inline multi-channel panning
        const channels = ['ch1', 'ch2', 'ch3', 'ch4'];
        let leftTerms: string[] = [];
        let rightTerms: string[] = [];

        channels.forEach(ch => {
            const conn = this.getInputConnection(block.id, ch);
            if (conn) {
                const sourceVar = this.getSourceVariable(conn);
                const level = block.parameterValues[`${ch}_level`] ?? 0.8;
                const pan = block.parameterValues[`${ch}_pan`] ?? 0.5;
                const levelF = this.formatFloat(level);
                const leftGain = this.formatFloat(Math.sqrt(1.0 - (pan as number)));
                const rightGain = this.formatFloat(Math.sqrt(pan as number));
                leftTerms.push(`(${sourceVar} * ${levelF} * ${leftGain})`);
                rightTerms.push(`(${sourceVar} * ${levelF} * ${rightGain})`);
            }
        });

        if (leftTerms.length > 0) {
            return [
                `sig_${name}_left = ${leftTerms.join(' + ')};`,
                `sig_${name}_right = ${rightTerms.join(' + ')};`,
            ];
        }
        return [
            `sig_${name}_left = 0.0f;`,
            `sig_${name}_right = 0.0f;`,
        ];
    }

    private generatePitchShifterCode(block: BlockInstance, name: string): string[] {
        // PitchShifter - simplified implementation note
        const audioIn = this.getInputConnection(block.id, 'in');
        const inputVar = audioIn ? this.getSourceVariable(audioIn) : '0.0f';
        const mix = block.parameterValues['mix'] ?? 1.0;

        // Note: Real pitch shifting requires buffer implementation
        // This is a placeholder that passes through with mix
        return [
            `// Note: Full pitch shifting requires delay buffer implementation`,
            `sig_${name}_out = ${inputVar} * ${this.formatFloat(mix)};`,
        ];
    }

    // ===========================================================================
    // OUTPUT ASSIGNMENT
    // ===========================================================================

    private generateOutputAssignment(): string[] {
        const outputBlock = this.patch.blocks.find(b => {
            const def = this.blockDefs.get(b.definitionId);
            return def?.id === 'audio_output';
        });

        if (!outputBlock) {
            return ['out[0][i] = 0.0f;', 'out[1][i] = 0.0f;'];
        }

        const leftConn = this.getInputConnection(outputBlock.id, 'left');
        const rightConn = this.getInputConnection(outputBlock.id, 'right');

        const leftVar = leftConn ? this.getSourceVariable(leftConn) : '0.0f';
        const rightVar = rightConn ? this.getSourceVariable(rightConn) : leftVar;

        return [`out[0][i] = ${leftVar};`, `out[1][i] = ${rightVar};`];
    }

    // ===========================================================================
    // MAIN FUNCTION
    // ===========================================================================

    private generateMain(): string {
        const lines: string[] = [];
        const blockSize = this.patch.metadata.blockSize;

        lines.push('int main(void) {');
        lines.push('    hw.Init();');
        lines.push(`    hw.SetAudioBlockSize(${blockSize});`);
        lines.push('    float sr = hw.AudioSampleRate();');
        lines.push('');
        lines.push('    // Initialize DSP modules');

        this.processingOrder.blocks.forEach(blockId => {
            const block = this.patch.blocks.find(b => b.id === blockId);
            if (!block) return;

            const def = this.blockDefs.get(block.definitionId);
            if (!def) return;

            // Skip I/O blocks and inline math blocks
            const skipBlocks = [
                'audio_output', 'audio_input', 'knob', 'key', 'encoder', 'gate_trigger_in',
                // Inline math/utility blocks (no DaisySP class)
                'vca', 'mixer', 'add', 'multiply', 'subtract', 'divide',
                'gain', 'bypass', 'sample_delay', 'cv_to_freq', 'mux', 'demux', 'linear_vca'
            ];
            if (skipBlocks.includes(def.id)) {
                return;
            }

            const instanceName = this.getInstanceName(block);

            // Special init handling for specific blocks
            if (def.id === 'whitenoise') {
                // WhiteNoise.Init() takes no arguments
                lines.push(`    ${instanceName}.Init();`);
            } else if (def.id === 'adsr') {
                // ADSR needs special SetTime handling with segment parameter
                lines.push(`    ${instanceName}.Init(sr);`);
                const attack = block.parameterValues['attack'] ?? 0.01;
                const decay = block.parameterValues['decay'] ?? 0.1;
                const sustain = block.parameterValues['sustain'] ?? 0.7;
                const release = block.parameterValues['release'] ?? 0.3;
                lines.push(`    ${instanceName}.SetTime(ADSR_SEG_ATTACK, ${this.formatFloat(attack)});`);
                lines.push(`    ${instanceName}.SetTime(ADSR_SEG_DECAY, ${this.formatFloat(decay)});`);
                lines.push(`    ${instanceName}.SetSustainLevel(${this.formatFloat(sustain)});`);
                lines.push(`    ${instanceName}.SetTime(ADSR_SEG_RELEASE, ${this.formatFloat(release)});`);
            } else {
                // Standard Init with sample rate
                lines.push(`    ${instanceName}.Init(sr);`);

                // Set default parameters (skip for ADSR as we handle it specially)
                def.parameters.forEach(param => {
                    const value = block.parameterValues[param.id] ?? param.defaultValue;
                    // Skip SetTime for ADSR as we handled it above
                    if (def.id === 'adsr' && param.cppSetter === 'SetTime') return;

                    if (param.cppSetter && value !== undefined) {
                        if (typeof value === 'number') {
                            lines.push(`    ${instanceName}.${param.cppSetter}(${this.formatFloat(value)});`);
                        } else if (typeof value === 'boolean') {
                            lines.push(`    ${instanceName}.${param.cppSetter}(${value});`);
                        } else if (param.type === 'enum' && param.enumValues) {
                            // Find the enum value's cppValue
                            const enumVal = param.enumValues.find(e => e.value === value);
                            if (enumVal?.cppValue) {
                                lines.push(`    ${instanceName}.${param.cppSetter}(${enumVal.cppValue});`);
                            }
                        }
                    }
                });
            }
        });

        lines.push('');
        lines.push('    hw.StartAdc();');
        lines.push('    hw.StartAudio(AudioCallback);');
        lines.push('');
        lines.push('    while(1) {}');
        lines.push('}');

        return lines.join('\n');
    }

    // ===========================================================================
    // MAKEFILE
    // ===========================================================================

    private generateMakefile(): string {
        const projectName = this.patch.metadata.name
            .replace(/[^a-zA-Z0-9]/g, '_')
            .toLowerCase();

        return `# Project Name
TARGET = ${projectName}

# Sources
CPP_SOURCES = main.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and target processor
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
OPT = -Os

# Includes
C_INCLUDES += -I$(DAISYSP_DIR)/Source

# Include Libraries
include $(SYSTEM_FILES_DIR)/Makefile
`;
    }

    // ===========================================================================
    // HELPERS
    // ===========================================================================

    private getInstanceName(block: BlockInstance): string {
        const def = this.blockDefs.get(block.definitionId);
        const base = def?.id || block.definitionId;
        return `${base}_${block.id.substring(0, 8)}`;
    }

    private getInputConnection(blockId: string, portId: string): Connection | undefined {
        return this.patch.connections.find(
            c => c.targetBlockId === blockId && c.targetPortId === portId
        );
    }

    private getSourceVariable(conn: Connection): string {
        const sourceBlock = this.patch.blocks.find(b => b.id === conn.sourceBlockId);
        if (!sourceBlock) return '0.0f';

        const sourceDef = this.blockDefs.get(sourceBlock.definitionId);
        if (!sourceDef) return '0.0f';

        const sourceInstanceName = this.getInstanceName(sourceBlock);
        const sourcePort = sourceDef.ports.find(p => p.id === conn.sourcePortId);

        if (sourcePort?.signalType === SignalType.CV) {
            return `cv_${sourceInstanceName}_${conn.sourcePortId}`;
        } else if (sourcePort?.signalType === SignalType.TRIGGER) {
            return `gate_${sourceInstanceName}_${conn.sourcePortId}`;
        } else {
            return `sig_${sourceInstanceName}_${conn.sourcePortId}`;
        }
    }

    /**
     * Format a number as a C++ float literal with decimal point
     * e.g., 440 -> "440.0f", 0.5 -> "0.5f"
     */
    private formatFloat(value: unknown): string {
        const num = Number(value);
        if (isNaN(num)) return '0.0f';
        // Ensure at least one decimal place
        const str = num.toString();
        if (str.includes('.')) {
            return `${num}f`;
        }
        return `${num}.0f`;
    }
    // ===========================================================================
    // PHASE 5: Hardware I/O
    // ===========================================================================

    private generateMidiNoteCode(block: BlockInstance, name: string): string[] {
        // Output code that relies on external MIDI handling
        // For now, we assume global variables are populated by a MIDI handler
        return [
            `// Block: ${block.id} (MidiNote)`,
            `// Note: Requires external MIDI handler to update these globals`,
            `// float ${name}_pitch = midi_pitch_global;`,
            `// float ${name}_velocity = midi_velocity_global;`,
            `// float ${name}_gate = midi_gate_global;`,
        ];
    }

    private generateMidiCCCode(block: BlockInstance, name: string): string[] {
        const channel = Number(block.parameterValues['channel'] ?? 1);
        const cc = Number(block.parameterValues['cc_number'] ?? 1);
        return [
            `// Block: ${block.id} (MidiCC Ch${channel} CC${cc})`,
            `// float ${name}_value = midi_cc_values[${channel}][${cc}];`
        ];
    }

    private generateCVInputCode(block: BlockInstance, name: string): string[] {
        const channel = Number(block.parameterValues['channel'] ?? 0);
        const bipolar = block.parameterValues['bipolar'] === true;
        // Daisy Field has 4 CV inputs: hw.cv[0] to hw.cv[3]
        // Cap channel at 3 to avoid access violations
        const safeChannel = Math.min(Math.max(0, channel), 3);

        let readCode = `float sig_${name}_out = hw.cv[${safeChannel}].Value();`;
        if (bipolar) {
            readCode += ` // Unipolar to Bipolar`;
            readCode += `\n    sig_${name}_out = (sig_${name}_out * 2.0f) - 1.0f;`;
        }
        return [readCode];
    }

    private generateCVOutputCode(block: BlockInstance, name: string): string[] {
        const channel = Number(block.parameterValues['channel'] ?? 0);
        const inConn = this.getInputConnection(block.id, 'in');
        const inVar = inConn ? this.getSourceVariable(inConn) : '0.0f';

        // Daisy Field CV Outs (DAC) - usually on Daisy Seed DAC pins
        // Channel 0 = DAC1, Channel 1 = DAC2
        const safeChannel = Math.min(Math.max(0, channel), 1);

        return [
            `// CV Output Ch${safeChannel}`,
            `hw.seed.dac.WriteValue((daisy::DacHandle::Channel)${safeChannel}, (uint16_t)(fminf(1.0f, fmaxf(0.0f, ${inVar})) * 4095.0f));`
        ];
    }

    private generateGateOutputCode(block: BlockInstance, name: string): string[] {
        const pin = Number(block.parameterValues['pin'] ?? 0);
        const gateConn = this.getInputConnection(block.id, 'gate');
        const gateVar = gateConn ? this.getSourceVariable(gateConn) : '0.0f';

        // Daisy Field has 2 Gate Outputs: hw.gate_out[0] and hw.gate_out[1] (if exposed)
        // Or using GPIO directly if DaisyField class doesn't wrap them convenienty.
        // Checking Field docs/source: hw.gate_out[i].Write(bool).
        const safePin = Math.min(Math.max(0, pin), 1);

        return [
            `// Gate Output Pin ${safePin}`,
            `// Assuming custom GateOutput wrapper or direct GPIO`,
            `dsy_gpio_write(&hw.gate_out_pins[${safePin}], ${gateVar} > 0.5f); // Pseudo-code, verify Field implementation`
        ];
    }

    private generateLEDOutputCode(block: BlockInstance, name: string): string[] {
        const pin = Number(block.parameterValues['pin'] ?? 0);
        const pwm = block.parameterValues['pwm'] === true;
        const brightConn = this.getInputConnection(block.id, 'brightness');
        const brightVar = brightConn ? this.getSourceVariable(brightConn) : '0.0f';

        // Daisy Field LED: hw.led[i] needed? The keyboard LEDs are usually controlled by KeyboardState or separately.
        // Assuming generic LED or specific Field LED (maybe the button LEDs?)
        return [
            `// LED Output Pin ${pin}`,
            `// Placeholder for Field LED control`,
            `// hw.led[${pin}].Set(${brightVar});`
        ];
    }
}
